# Generated by Django 5.0 on 2023-12-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='verse',
        ),
        migrations.AddField(
            model_name='post',
            name='verses',
            field=models.ManyToManyField(related_name='posts', to='quran.verse'),
        ),
    ]
